name: Build n Release Synology Recover Data

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-zip:
    name: Build zip
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get release tag
        id: get_tag
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            tag=$(curl -s https://api.github.com/repos/007revad/Synology_Recover_Data/releases/latest \
              | jq -r .tag_name)
            echo "tag=$tag" >> $GITHUB_OUTPUT
          fi

      - name: Create zip
        run: |
          zip Synology_Recover_Data.zip syno_recover_data.sh

      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          files: Synology_Recover_Data.zip
          make_latest: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
